version: '3.4'

services:
  webhookapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${HOME}/.aspnet/https:/root/.aspnet/https:ro
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets
   