version: '3.4'

services:
  webhookapi:
    image: ${DOCKER_REGISTRY-}webhookapi
    build:
      context: .
      dockerfile: src/webHookApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8080:80"
      - "7443:443"
    volumes:
      - ${HOME}/.aspnet/https:/root/.aspnet/https:ro
      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets
  